[package]
name = "metafrost2"
version = "0.1.0"
authors = ["Rhys Newell <rhys.newell@uqconnect.edu.au>"]

[dependencies]
log = "^0.4.5"
env_logger = "^0.5.13"
clap = "^2.32.0"

[dev-dependencies]
assert_cli = "0.6.*"
